# The properties of this server.
server:
  # The identity and credentials of this server.
  identity:
    # identity.id denotes the id of the server.
    id: orion-server1
    # identity.certificatePath denotes the path to the x509 certificate
    # of the node. This certificate and associated key is used in all
    # client facing communication, as well as for signing blocks and
    # transaction replies.
    certificatePath: ./deployment/crypto/server/server.pem
    # identity.keyPath denotes the path to the private key of the node.
    keyPath: ./deployment/crypto/server/server.key
  # The listen address and port of the network interface used for client
  # communication. The external address (or host name) of this interface
  # must be accessible to clients, and is declared in:
  # consensus.members[i].nodeHost
  # consensus.members[i].nodePort
  # where consensus.members[i].nodeID == node.identity.id
  network:
    # network.address denotes the listen address
    address: 127.0.0.1
    # network.port denotes the listen port
    port: 6001
  database:
    # database.name denotes the name of the underlying
    # database engine
    name: leveldb
    # database.ledgerDirectory denotes the root path
    # where we store all ledger data
    ledgerDirectory: ledger
  queueLength:
    # queueLength.transaction denotes the maximum
    # queue length of waiting transactions
    transaction: 1000
    # queueLength.transactionBatch denotes the maximum
    # queue length of waiting reordered batches of transactions
    reorderedTransactionBatch: 100
    # queueLength.block denotes the maximum queue length
    # of waiting blocks
    block: 100
  # logLevel can be debug, info, warn, err, and panic
  logLevel: info
  tls:
    enabled: false
    # Require client certificates / mutual TLS for inbound connections.
    clientAuthRequired: false
    # X.509 certificate used for TLS server
    serverCertificatePath: ./testdata/tls/server/server.cert
    # Private key for TLS server
    serverKeyPath: ./testdata/tls/server/server.key
    caConfig:
      # The paths to root certificates. At least one is required. for example:
      #   rootCACertsPath: ./testdata/rootcaA.cert, ./testdata/rootcaB.cert
      rootCACertsPath: ./testdata/tls/CA/rootca.cert
      # The paths to intermediate certificates. Optional. For example:
      #   intermediateCACertsPath: ./testdata/cluster/midcaA.cert, ./testdata/cluster/midcaB.cert
      intermediateCACertsPath: ./testdata/tls/CA/midca.cert

# blockCreation carries block creation parameters.
blockCreation:
  # blockCreation.blockSize denotes the maximum allowed size of the block in MB
  maxBlockSize: 2

  # maxTransactionCountPerBlock denotes the maximum allowed number of
  # transactions per block
  maxTransactionCountPerBlock: 1

  # blockTimeout denotes the block timeout in milliseconds
  blockTimeout: 50ms

# The replication settings specific to this server.
replication:
  # The directory for the Raft WAL (write ahead log).
  walDir: "./tmp/etcdraft/wal"

  # The directory for the Raft snapshots.
  snapDir: "./tmp/etcdraft/snapshot"

  # The listen address and port for intra-cluster communication.
  # The external address (or host name) of this interface
  # must be accessible from all other servers (a.k.a. "peers"),
  # and is declared in the shared configuration:
  # consensus.members[i].peerHost
  # consensus.members[i].peerPort
  # where consensus.members[i].nodeID == node.identity.id
  network:
    # The listen address
    address: 127.0.0.1
    # The listen port
    port: 7050

  # TLS settings for intra-cluster communication.
  tls:
    # Require server-side TLS.
    enabled: false
    # Require client certificates / mutual TLS for inbound connections.
    clientAuthRequired: false
    # X.509 certificate used for TLS server
    serverCertificatePath: ./testdata/cluster/server.cert
    # Private key for TLS server
    serverKeyPath: ./testdata/cluster/server.key
    # X.509 certificate used for creating TLS client connections.
    clientCertificatePath: ./testdata/cluster/client.cert
    # Private key used for creating TLS client connections.
    clientKeyPath: ./testdata/cluster/client.key
    # cluster.tls.caConfig defines the paths to the x509 certificates
    # of the root and intermediate certificate authorities that issued
    # all the certificates used for intra-cluster communication.
    caConfig:
      # The paths to root certificates. At least one is required. for example:
      #   rootCACertsPath: ./testdata/rootcaA.cert, ./testdata/rootcaB.cert
      rootCACertsPath: ./testdata/cluster/rootca.cert

      # The paths to intermediate certificates. Optional. For example:
      #   intermediateCACertsPath: ./testdata/cluster/midcaA.cert, ./testdata/cluster/midcaB.cert
      intermediateCACertsPath: ./testdata/cluster/midca.cert


# bootstrap specifies the method of starting a new node with an empty ledger and database.
bootstrap:
  # method specifies how to use the bootstrap file:
  # - 'genesis' means to load it as the initial configuration that will be converted into the ledger's genesis block and
  #    loaded into the database when the server starts with an empty ledger.
  # - 'join' means to load it as a temporary configuration that will be used to connect to existing cluster members
  #    and on-board by fetching the ledger from them, rebuilding the database in the process (not supported yet).
  method: genesis
  # file contains the initial configuration that will be used to bootstrap the node, as specified by the method, above.
  file: ./deployment/config-local/bootstrap-shared-config.yaml
